### ISSUE TITLE
挂了吗？

### ISSUE THREAD

**Issue by YeFei572** [enzeberg/about-tonzhon#1]
好几天不能访问了。

**Comment by wariot221zjsru** [comment]
挂了。
Tonzhon is closed for the political reason.Someone said that the Tonzhon have sexy music, but that is from Wangyi Cloud.
为什么铜钟（tonzon.com）打不开了？是这几天在维护吗？ - 正阳的回答 - 知乎
https://www.zhihu.com/question/636371332/answer/3399814471
This is the situation described in zhihu.

**Comment by wariot221zjsru** [comment]
https://github.com/enzeberg/tonzhon-lite-mobile/issues/1

**Comment by wariot221zjsru** [comment]
I suggest that the website can be moved to Servicers of other countries.

**Comment by wariot221zjsru** [comment]
I suggest that the website can be moved to Servicers of other countries.

**Comment by wariot221zjsru** [comment]
![v2-932acf8768c0621002ba5c3aedd295fa_720w](https://github.com/enzeberg/about-tonzhon/assets/114033742/4c3e96ab-042c-44ae-bd4d-f63016743210)

**Comment by wariot221zjsru** [comment]
The cultural control of cn...

**Comment by wariot221zjsru** [comment]
> The cultural control of cn...

So...

**Comment by wariot221zjsru** [comment]
@enzeberg
